language: scala

matrix:
  include:
    - jdk: oraclejdk8
      scala: 2.10.6
      env: SCALAZ_VERSION=7.1.11
    - jdk: oraclejdk8
      scala: 2.11.8
      env: SCALAZ_VERSION=7.1.11

branches:
  only:
    - master

before_script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi"

script:
  - |
    if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      if [ $RELEASE_ON_PUSH = 'false' ]; then
        sbt ++$TRAVIS_SCALA_VERSION test coverageReport
      else
        sbt ++$TRAVIS_SCALA_VERSION 'release with-defaults'
      fi
    else
      sbt ++$TRAVIS_SCALA_VERSION test coverageReport
    fi
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - "bash <(curl -s https://codecov.io/bash) -r $TRAVIS_REPO_SLUG -t $CODECOV_TOKEN"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

env:
  global:
    - secure: "DZcuAGkuqTRPUXbk3lLS6uq3iGcMOdiqC95b/EkMnlyxvfQHvo7aDOXFtzv2GL1pWXBY969qy/YHnqUIMjP8eLBIO588mPUotlHztgVaG8hnf8YCfWjZmwGRz79/sZNlugBcIyYYTK7Whcgg5ssVWbJ/ubU09TF2dCiIMQhzq2U="
    - secure: "GCV0F4pk1mv3u2hzRKdAZtoWuzWE9+Bb2g5KuYD+iiRroyEpwAiOzk174ARUU/BmqX87ZV7mnsXJfRxYqD8Z3dokxLAGQaSjEIwawuaDUACwh9BIIsfIFtravy/VuYv6PS7kv34lWo0bHXPDbU8w/A37/vIyu/Uh5pqfYtJhcg8="
    - secure: "a8EwYFwjtxeYs/EQGLK0CnHN4jj1MTsXLdIR7LviohoB0fws1IvlTJHnPnbaVCcUB+ghoblt/tLLe8foSKWedfWkf9KBBbpLny1RW69eHp7qAUdgo6KoJZrjbKj7NYN2UrKgb/dUn7Gm+CmbNenwYoTmmdmkLDPDfgm3DACsOIE="
